name: fractal
adopt-info: fractal
version: '0.1.29'

base: core18
grade: stable
confinement: strict

parts:
  desktop-gtk3:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
    - build-essential
    - libgtk-3-dev
    stage-packages:
    - libxkbcommon0  # XKB_CONFIG_ROOT
    - ttf-ubuntu-font-family
    - dmz-cursor-theme
    - light-themes
    - adwaita-icon-theme
    - gnome-themes-standard
    - shared-mime-info
    - libgtk-3-0
    - libgdk-pixbuf2.0-0
    - libglib2.0-bin
    - libgtk-3-bin
    - unity-gtk3-module
    - libappindicator3-1
    - locales-all
    - xdg-user-dirs
    - ibus-gtk3
    - libibus-1.0-5
    - fcitx-frontend-gtk3

  # gspell:
  #   after: [desktop-gtk3]
  #   plugin: autotools
  #   source: https://gitlab.gnome.org/GNOME/gspell.git
  #   source-tag: 1.8.1
  #   configflags:
  #     - --prefix=/usr
  #   build-packages:
  #     - gtk-doc-tools
  #     - iso-codes
  #     - libenchant-dev
  #     - pkg-config

  fractal:
    after: [desktop-gtk3]
    plugin: meson
    source: https://gitlab.gnome.org/World/fractal.git
    source-tag: '0.1.29'
    parse-info: [usr/share/appdata/org.gnome.Fractal.appdata.xml]
    # override-pull: |
    #   snapcraftctl pull
    #   last_committed_tag="$(git describe --tags --abbrev=0)"
    #   last_released_tag="$(snap info $SNAPCRAFT_PROJECT_NAME | awk '$1 == "beta:" { print $2 }')"
    #   # If the latest tag from the upstream project has not been released to
    #   # beta, build that tag instead of master.
    #   if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
    #     git fetch
    #     git checkout "${last_committed_tag}"
    #     snapcraftctl set-version "$(echo "${last_committed_tag}" | sed -E -e "s|^$SNAPCRAFT_PROJECT_NAME-?||i")"
    #   else
    #     snapcraftctl set-version "$(git rev-parse --short HEAD)"
    #   fi
    override-build: |
      # TODO: remove
      cargo update -p petgraph
      snapcraftctl build
    meson-parameters:
      - --buildtype=release
      - --prefix=/usr
    build-packages:
      - cmake
      - libgmp-dev
      - libgstreamer-plugins-bad1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer1.0-dev
      - libgtksourceview-3.0-dev
      - libsecret-1-dev
      - libssl-dev
      - rustc
    # stage-packages:
    #   - libgstreamer-plugins-bad1.0-0
    #   - libgstreamer-plugins-base1.0-0
    #   - libgstreamer1.0
    #   - libgtksourceview-3.0-1
    #   - libsecret-1-0
    #   - libssl1.0

slots:
  dbus-fractal:
    interface: dbus
    bus: session
    name: org.gnome.Fractal

plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes:gtk-3-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes:icon-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes:sounds-themes
  gnome-3-28-1804:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-28-1804:gnome-3-28-1804

apps:
  fractal:
    command: desktop-launch $SNAP/usr/bin/fractal
    common-id: org.gnome.Fractal.desktop
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - network
      - password-manager-service
      - wayland
      - x11
